---
title: "p8105_hw5_nz2333"
author: "nz2333"
date: "11/20/2021"
output: github_document
---

```{r}
library(tidyverse)
library(tidyr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Porblem 2
```{r}
df_p2 = tibble(
  file = list.files(
  "./data"))

read_data = function(name) {
  read_csv(str_c("./data/", name))
}

df_p2 = df_p2 %>%
  mutate(data = map(file, read_data)) %>%
  unnest(data)

final_data = df_p2 %>%
  mutate(file = str_replace(file, ".csv", "")) %>%
  separate(file, into = c("Arm", "ID"), sep = "_", remove = FALSE)
```

_Spaghetti plot_
```{r}
plot = final_data %>%
  pivot_longer(week_1:week_8, 
               names_to = "Week", 
               values_to = "Obs") %>%
  ggplot(aes(x = Week, y = Obs, group = file, color = Arm)) +
  geom_line() +
  labs(x = "Week", 
       y = "Observations on each subject",
       title = "Observations on each subject over time")

plot
```

The observations are similar at the beginning. The control arm fluctuated but show a steady trend over time. The experimental arms show positive slopes that the observations are increasing over time. 

## Porblem 3
```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

```{r}
fill_nas = function(var) {
  if (is.numeric(var)) {
    var[is.na(var)] = mean(var, na.rm = TRUE)
  }
  else if (!is.numeric(var)) {
    var[is.na(var)] = "virginica"
  }
  return(var)
}
```

```{r}
map(iris_with_missing, fill_nas)
```


